version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: Amgo_user
      POSTGRES_PASSWORD: AmgoPassword
      POSTGRES_DB: TestDb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: my_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
